'use client'
import Link from 'next/link'
import { useMemo, useState } from 'react'

// data omitted comments not used
const scenarios = [
  { id: '3', label: '3 Story', recommended: '3-Story By-Right + Preserve 6-Story Optionality', summary: ['By-right control case', 'Fastest executable path', 'Lowest entitlement complexity', 'Lowest capital intensity', 'Shortest construction duration'], value: 'Value creation at this stage increases PE underwriting confidence.', impacts: [{ label: 'Entitlement Intensity', value: 'Low' }, { label: 'Capital Coordination', value: 'Moderate' }, { label: 'Construction Duration', value: '14–18 months' }, { label: 'Delivery Complexity', value: 'Controlled' }] },
  { id: '6', label: '6 Story', recommended: '6-Story Rezoning Case with Structured Outreach', summary: ['Realistic rezoning path', 'Stronger unit count', 'Balanced timeline', 'Moderate entitlement lift'], value: 'Balanced upside supports stronger valuation while preserving execution discipline.', impacts: [{ label: 'Entitlement Intensity', value: 'Moderate' }, { label: 'Capital Coordination', value: 'Moderate/High' }, { label: 'Construction Duration', value: '18–22 months' }, { label: 'Delivery Complexity', value: 'Moderate' }] },
  { id: '8', label: '8 Story', recommended: '8-Story Optimized Yield with Early City Positioning', summary: ['Stronger condo stack', 'Improved IRR', 'Moderate/high entitlement complexity', 'Requires disciplined stakeholder coordination'], value: 'Higher yield potential requires stronger sequencing and entitlement control.', impacts: [{ label: 'Entitlement Intensity', value: 'Moderate/High' }, { label: 'Capital Coordination', value: 'High' }, { label: 'Construction Duration', value: '20–24 months' }, { label: 'Delivery Complexity', value: 'High' }] },
  { id: '10', label: '10 Story', recommended: '10-Story Maximum Upside Reserve Path', summary: ['Highest density', 'PE preferred upside case', 'Longest city path', 'Highest process complexity'], value: 'Maximum density can deliver strong upside, but requires prolonged city and capital coordination.', impacts: [{ label: 'Entitlement Intensity', value: 'High' }, { label: 'Capital Coordination', value: 'Very High' }, { label: 'Construction Duration', value: '22–28 months' }, { label: 'Delivery Complexity', value: 'Very High' }] }
]
const matrix = [
  ['3 Stories — By Right', ['Fastest path', 'Lowest entitlement risk', 'Supported by current zoning assumptions', 'Expected construction window: 14–18 months']],
  ['6 Stories — Moderate Lift', ['Realistic rezoning path', 'Stronger unit count', 'Balanced timeline', 'Expected construction window: 18–22 months']],
  ['8 Stories — Optimized Yield', ['Stronger condo stack', 'Improved IRR', 'Moderate/high entitlement complexity', 'Expected construction window: 20–24 months']],
  ['10 Stories — Maximum Upside', ['Highest density', 'PE preferred upside case', 'Longest city path', 'Expected construction window: 22–28 months']]
] as const
const phases = [
  { n: 1, nav: 'Alignment', t: 'Project Alignment', s: 'Complete', p: 100, purpose: 'Confirm ownership goals, preferred development posture, hold/sell options, and optionality logic before additional spend.', decisionGate: 'Approve project basis and preferred early path.', ownerAction: 'Confirm strategic posture and immediate budget tolerance.', keyDeliverable: 'Alignment memo and initial decision framework.', riskWatch: 'Misaligned sponsor assumptions may create downstream resets.', capitalTrigger: 'Release predevelopment coordination budget.', nextStep: 'Carry approved basis into site, market, and diligence sequencing.' },
  { n: 2, nav: 'Site + Due Diligence', t: 'Site Studies + Due Diligence', s: 'In Progress', p: 42, purpose: 'Confirm site conditions, environmental exposure, infrastructure constraints, access, and physical development risks.', decisionGate: 'Confirm if findings support by-right advancement or higher-density entitlement study.', ownerAction: 'Approve remaining due diligence scope and survey/title coordination.', keyDeliverable: 'ESA status, geotech summary, survey/ALTA scope, and risk register.', riskWatch: 'Environmental legacy, tank closure history, utilities, and access constraints.', capitalTrigger: 'Release next tranche only after site risks are understood.', nextStep: 'Complete ESA review and align survey notice to proceed.' },
  { n: 3, nav: 'Survey + Title', t: 'Survey + ALTA / Title', s: 'In Progress', p: 48, purpose: 'Establish the legal and physical base map for design, entitlement strategy, easements, access, and lender diligence.', decisionGate: 'Confirm legal base is sufficient for design and city-facing planning.', ownerAction: 'Approve survey notice to proceed.', keyDeliverable: 'ALTA/title package, boundary/topo, easements, ROW, and utility locate coordination.', riskWatch: 'Late survey findings can delay concept lock and entitlement path.', capitalTrigger: 'Release concept design spend after survey base is received.', nextStep: 'Align title inputs and issue survey authorization.' },
  { n: 4, nav: 'Market Validation', t: 'Market + Product Validation', s: 'In Progress', p: 56, purpose: 'Stress-test product mix, retail frontage assumptions, pricing bands, affordability positioning, and likely exit paths.', decisionGate: 'Confirm demand-backed product posture.', ownerAction: 'Review comp findings and preferred use mix.', keyDeliverable: 'Market memo, product mix options, pricing sensitivity, and retail frontage assumptions.', riskWatch: 'Weak comps or affordability gaps may change scenario feasibility.', capitalTrigger: 'Release investor material budget after baseline validation.', nextStep: 'Convert comp findings into capital packet narrative.' },
  { n: 5, nav: 'Capital Formation', t: 'Capital Formation', s: 'In Progress', p: 63, purpose: 'Build a credible capital strategy matched to development path, entitlement complexity, and execution timing.', decisionGate: 'Select preliminary capital pathway for pre-entitlement and entitlement periods.', ownerAction: 'Prioritize sponsor equity, PE conversations, lender outreach, and public funding options.', keyDeliverable: 'Sources and uses, investor narrative, outreach tracker, and preliminary capital stack.', riskWatch: 'Capital timing mismatch with city process can delay execution.', capitalTrigger: 'Sponsor approval of phased outreach and diligence budget.', nextStep: 'Launch structured PE and lender conversations after market memo lock.' },
  { n: 6, nav: 'Rezoning Strategy', t: 'Rezoning + City Strategy', s: 'Queued', p: 18, purpose: 'Define the city-facing pathway from current zoning to preferred height, density, affordability, and neighborhood benefit.', decisionGate: 'Approve rezoning strategy and city engagement sequence.', ownerAction: 'Align district outreach language and next meeting priorities.', keyDeliverable: 'Rezoning strategy memo, outreach calendar, city path matrix, and public-benefit narrative.', riskWatch: 'Community and policy feedback may require iterative massing revisions.', capitalTrigger: 'Release entitlement consulting and outreach budget after path selection.', nextStep: 'Sequence district meetings and compare 3 / 6 / 8 / 10-story pathways.' },
  { n: 7, nav: 'Design Team', t: 'Design Team Assembly', s: 'Queued', p: 0, purpose: 'Architect, GC, and project advisory input are being coordinated to support feasibility, entitlement strategy, and construction planning.', decisionGate: 'Confirm architect, GC, and project advisory coordination milestones and baseline deliverable calendar.', ownerAction: 'Confirm architect, GC advisory, civil, structural, MEP, traffic/parking, and land-use support.', keyDeliverable: 'Consultant roster, scopes, fee alignment, and coordination protocol.', riskWatch: 'Delayed onboarding can compress downstream concept and DD timelines.', capitalTrigger: 'Release design retainers after path and budget validation.', nextStep: 'Finalize architect shortlist and issue project advisory + consultant group selections.' },
  { n: 8, nav: 'Concept + Massing', t: 'Concept Design + Massing', s: 'Queued', p: 0, purpose: 'Translate strategy into buildable site and massing options linked to each height pathway.', decisionGate: 'Select preferred concept and fallback option for entitlement.', ownerAction: 'Review preferred massing options, retail frontage, parking assumptions, access strategy, and neighborhood-facing design considerations.', keyDeliverable: 'Concept package, option matrix, site plan, and recommendation set.', riskWatch: 'Too many options can dilute schedule discipline.', capitalTrigger: 'Release schematic development budget after concept approval.', nextStep: 'Begin a coordinated concept review once the survey base is finalized, including building massing, retail frontage, parking assumptions, site access, and neighborhood interface.' },
  { n: 9, nav: 'DD + Engineering', t: 'DD + Engineering', s: 'Queued', p: 0, purpose: 'Advance the preferred concept into coordinated design-development and engineering content.', decisionGate: 'Approve DD freeze and authorize permit document finalization.', ownerAction: 'Confirm scope, cost alignment, utility coordination, and constructability path.', keyDeliverable: 'DD drawing set, coordinated systems narrative, updated estimate, and consultant logs.', riskWatch: 'Cost escalation may require value engineering or scope prioritization.', capitalTrigger: 'Release engineering budget after concept gate approval.', nextStep: 'Set DD milestones and monthly cost alignment reviews.' },
  { n: 10, nav: 'Permit + Financing', t: 'Permit + Financing', s: 'Queued', p: 0, purpose: 'Align permit readiness with debt/equity close requirements and final underwriting.', decisionGate: 'Authorize construction financing close and permit conversion sequence.', ownerAction: 'Review permit set, lender package, appraisal support, GMP alignment, and draw schedule.', keyDeliverable: 'Permit checklist, lender diligence index, financing close checklist, and GMP draft.', riskWatch: 'Appraisal and pricing gaps may require structure or scope adjustments.', capitalTrigger: 'Release closing costs and GMP support budget upon permit milestone confidence.', nextStep: 'Sequence lender diligence with permit review timelines.' },
  { n: 11, nav: 'Mobilization', t: 'Preconstruction + Mobilization', s: 'Queued', p: 0, purpose: 'Convert planning into field-ready execution controls and launch conditions.', decisionGate: 'Confirm site is fully mobilized and field controls are active.', ownerAction: 'Approve NTP, logistics plan, procurement schedule, reporting cadence, and site controls.', keyDeliverable: 'Executed contracts, mobilization plan, baseline schedule, and reporting protocol.', riskWatch: 'Long-lead procurement delays can impact structural start sequencing.', capitalTrigger: 'Release initial construction draw after NTP and mobilization checklist completion.', nextStep: 'Finalize long-lead buyout strategy and site logistics review.' },
  { n: 12, nav: 'Construction', t: 'Vertical Construction', s: 'Queued', p: 0, purpose: 'Deliver the building through sequenced field execution, quality controls, inspections, and turnover readiness.', decisionGate: 'Approve major milestone completions before entering subsequent sub-bands.', ownerAction: 'Monitor schedule, budget, inspections, change orders, quality control, and draw verification.', keyDeliverable: 'Milestone completion records, inspection logs, turnover-ready systems.', riskWatch: 'Procurement, labor, and weather variance can affect sequencing and cost control.', capitalTrigger: 'Draw releases tied to verified monthly progress and inspection milestones.', nextStep: 'Finalize sequence controls by sub-band prior to NTP.' },
  { n: 13, nav: 'Closeout', t: 'Closeout + Exit', s: 'Queued', p: 0, purpose: 'Complete turnover, close contractual obligations, and execute the final hold/sell/refinance/exit pathway.', decisionGate: 'Approve final exit strategy execution and closeout sign-off.', ownerAction: 'Review punch list, warranties, lien releases, final reconciliation, and operating/exit plan.', keyDeliverable: 'CO/TCO records, turnover binders, warranty registry, final draw reconciliation.', riskWatch: 'Extended punch-list and tenant turnover timing may shift final reconciliation.', capitalTrigger: 'Release retainage and closeout funds upon completion verification.', nextStep: 'Define closeout governance and exit timeline before vertical completion.' }
]
const statusClass: Record<string, string> = { Complete: 'bg-emerald-100 text-emerald-800', 'In Progress': 'bg-amber-100 text-amber-800', Queued: 'bg-slate-200 text-slate-700' }

export default function RoadmapDashboard() {
  const [activeScenario, setActiveScenario] = useState('3')
  const active = useMemo(() => scenarios.find((s) => s.id === activeScenario) ?? scenarios[0], [activeScenario])

  return <div className="min-w-0 max-w-full space-y-10 pb-14">
    <section className="rounded-2xl border border-[#d4af37]/50 bg-[#0d1b2a] p-6 text-[#f8fafc] md:p-8">
      <h1 className="text-3xl font-bold md:text-4xl">5501 E. 33rd Development Execution Roadmap</h1>
      <p className="mt-3 max-w-4xl text-sm text-slate-200 md:text-base">A disciplined project index for site diligence, entitlement strategy, capital sequencing, consultant coordination, and construction readiness.</p>
      <div className="mt-5 flex flex-wrap gap-2 text-xs font-semibold"><span className="rounded-full border border-[#d4af37]/60 px-3 py-1">Geotech reviewed</span><span className="rounded-full border border-[#d4af37]/60 px-3 py-1">ESA active</span><span className="rounded-full border border-[#d4af37]/60 px-3 py-1">Survey / title pending</span><span className="rounded-full border border-[#d4af37]/60 px-3 py-1">Height path under evaluation</span><span className="rounded-full border border-[#d4af37]/60 px-3 py-1">Capital narrative forming</span></div>
      <div className="mt-6 grid gap-3 sm:grid-cols-3"><Link href="/project" className="rounded-lg bg-white px-4 py-2 text-center text-sm font-semibold text-[#0d1b2a]">Return to Project Overview</Link><a href="#scenario" className="rounded-lg border border-[#d4af37] px-4 py-2 text-center text-sm font-semibold">Review Height Path Options</a><a href="#timeline" className="rounded-lg border border-[#d4af37] px-4 py-2 text-center text-sm font-semibold">Review Live Milestones</a></div>
    </section>
    <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-bold">Owner Action Dashboard</h2><ul className="mt-3 grid gap-2 text-sm md:grid-cols-2">{['Confirm preferred height path for early city discussions','Approve survey / title notice to proceed','Align community outreach language','Sequence architect and consultant input','Advance investor introductions and PE follow-up calls','Define next predevelopment budget tranche'].map((a) => <li key={a} className="rounded-lg bg-[#f8fafc] p-3">{a}</li>)}</ul></section>
    <section className="grid gap-3 md:grid-cols-3">{['Current Stage: Due Diligence + Market Validation','Site Studies: Geotech Reviewed / ESA Active','Entitlement: Pre-Rezoning Strategy','Capital: PE Outreach + Comp Validation','Design Readiness: Architect / GC / project advisory group assembled','Construction Readiness: 3-Story By-Right Feasible'].map((c) => <div key={c} className="rounded-lg border border-[#d4af37]/60 bg-white p-4 text-sm font-medium">{c}</div>)}</section>
    <section id="scenario" className="space-y-4"><h2 className="text-2xl font-bold">Height Scenario Matrix</h2><div className="grid gap-4 md:grid-cols-2">{matrix.map(([title, bullets]) => <div key={title} className="rounded-xl border border-slate-200 bg-white p-4"><h3 className="font-semibold">{title}</h3><ul className="mt-2 space-y-1 text-sm text-slate-700">{bullets.map((b) => <li key={b}>• {b}</li>)}</ul></div>)}</div><div className="rounded-xl bg-[#0d1b2a] p-5 text-white"><div className="flex flex-wrap gap-2">{scenarios.map((s) => <button key={s.id} onClick={() => setActiveScenario(s.id)} className={`rounded-full px-3 py-1 text-sm ${activeScenario === s.id ? 'bg-[#d4af37] text-[#0d1b2a] font-semibold' : 'border border-slate-400'}`}>{s.label}</button>)}</div><p className="mt-4 text-sm font-semibold text-[#d4af37]">Recommended Today: {active.recommended}</p><ul className="mt-2 text-sm">{active.summary.map((s) => <li key={s}>• {s}</li>)}</ul><p className="mt-3 text-sm">{active.value}</p><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{active.impacts.map((i) => <div key={i.label} className="rounded-lg border border-[#d4af37]/40 p-2 text-xs"><p className="text-slate-300">{i.label}</p><p className="font-semibold">{i.value}</p></div>)}</div></div></section>
    <section className="rounded-xl bg-[#0d1b2a] p-4 text-white"><p className="text-center text-lg font-semibold">Cost certainty improves as unknowns are converted into decisions.</p></section>
    <section id="timeline" className="roadmap-layout grid min-w-0 max-w-full items-start gap-4 lg:grid-cols-[260px_minmax(0,1fr)] lg:gap-8"><aside className="roadmap-phase-index min-w-0 max-w-full lg:sticky lg:top-[calc(var(--site-header-height,88px)+24px)] lg:h-fit lg:w-full lg:max-w-[260px]"><div className="flex flex-wrap gap-2 pb-1 lg:flex lg:flex-col lg:flex-nowrap lg:gap-3 lg:pb-0">{phases.map((p) => <a key={p.n} href={`#phase-${p.n}`} className="phase-pill inline-flex min-h-11 min-w-0 items-center gap-3 rounded-full border border-[#0d1b2a]/20 bg-white px-3 py-2 text-xs font-semibold text-[#0d1b2a] transition hover:border-[#d4af37] hover:bg-[#0d1b2a] hover:text-white lg:mb-0 lg:w-full lg:rounded-full lg:px-4 lg:py-2.5 lg:text-sm"><span className="phase-pill-number inline-flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[#0d1b2a] text-[10px] text-white">{p.n}</span><span className="phase-pill-label min-w-0 [overflow-wrap:anywhere] break-words whitespace-normal">{p.nav}</span></a>)}</div></aside><div className="roadmap-content min-w-0 max-w-full space-y-3">{phases.map((p) => <article id={`phase-${p.n}`} key={p.n} className="phase-card min-w-0 max-w-full rounded-xl border border-slate-200 bg-white p-4 md:p-5"><div className="flex min-w-0 flex-wrap items-start justify-between gap-2"><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Phase {p.n}</p><h3 className="min-w-0 [overflow-wrap:anywhere] break-words whitespace-normal text-lg font-bold text-[#0d1b2a]">{p.t}</h3></div><span className={`rounded-full px-2 py-1 text-xs font-semibold ${statusClass[p.s]}`}>{p.s}</span></div><div className="mt-3 h-1.5 rounded-full bg-slate-200"><div className="h-1.5 rounded-full bg-[#d4af37]" style={{ width: `${p.p}%` }} /></div><div className="mt-3 min-w-0 rounded-lg bg-slate-50 p-3 text-sm text-slate-700"><span className="font-semibold text-[#0d1b2a]">Purpose:</span> {p.purpose}</div><div className="phase-detail-grid mt-3 grid min-w-0 grid-cols-1 gap-2 text-sm sm:grid-cols-2 lg:grid-cols-3">{[{ label: 'Decision Gate', value: p.decisionGate }, { label: 'Owner Action', value: p.ownerAction }, { label: 'Key Deliverable', value: p.keyDeliverable }, { label: 'Risk Watch', value: p.riskWatch }, { label: 'Capital Trigger', value: p.capitalTrigger }, { label: 'Next Step', value: p.nextStep }].map((item) => <div key={item.label} className="phase-detail-card min-w-0 rounded-lg border border-slate-200 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{item.label}</p><p className="mt-1 min-w-0 [overflow-wrap:anywhere] break-words whitespace-normal text-sm text-slate-700">{item.value}</p></div>)}</div></article>)}</div></section>
    <section className="grid gap-4 md:grid-cols-2"><div className="rounded-xl border p-4"><h3 className="font-bold">From Existing Zoning to Height Upside</h3><ol className="mt-2 grid gap-1 text-sm">{['Complete site studies','Complete survey + legal base','Confirm 3 / 6 / 8 / 10 massing paths','District outreach','Neighborhood positioning','Select preferred height path','Rezoning submission','City comments','Revisions','Approval path','Permit conversion'].map((s, i) => <li key={s}>{i + 1}. {s}</li>)}</ol></div><div className="rounded-xl border p-4"><h3 className="font-bold">City Review and Influence Path</h3><p className="mt-2 text-sm">District Office → Planning Staff → Neighborhood Positioning → Rezoning Review → Public Process → Council / Approval Path → Permit Conversion</p></div></section>
    <section className="rounded-xl bg-[#0d1b2a] p-5 text-white"><h3 className="text-xl font-bold">Live Market Intelligence</h3><div className="mt-3 grid gap-3 md:grid-cols-4">{['Condo Sales Validation','Workforce Rental Logic','Retail Frontage Assumptions','Exit Path Options'].map((x) => <div key={x} className="rounded-lg border border-[#d4af37]/40 p-3 text-sm">{x}</div>)}</div></section>
    <section className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{['Environmental legacy review','Tank closure verification','Entitlement risk','Parking / massing tradeoffs','Construction cost escalation','Appraisal gap','Capital close timing','Interest rate sensitivity'].map((r) => <div key={r} className="rounded-lg border bg-white p-3 text-sm">{r}</div>)}</div><div className="rounded-xl bg-[#0d1b2a] p-4 text-white"><p className="font-semibold">Parallel Workstreams</p><div className="mt-2 flex flex-wrap gap-2">{['PE outreach','City meetings','Architect interviews','GC benchmarking','ESA verification','Survey + title','Comp refresh','Neighborhood narrative','Lender conversations'].map((t) => <span key={t} className="rounded-full border border-[#d4af37]/50 px-3 py-1 text-xs">{t}</span>)}</div></div></section>
    <section className="grid gap-4 md:grid-cols-2"><div className="rounded-xl border p-4"><h3 className="font-bold">Owner Capital Exposure by Milestone</h3><ul className="mt-2 text-sm"><li>• Studies</li><li>• Design</li><li>• City / Entitlement</li><li>• Preconstruction</li></ul></div><div className="rounded-xl border p-4"><h3 className="font-bold">Capital Sequencing by Tranche</h3><ul className="mt-2 text-sm"><li>• Early Owner Soft Cost Tranche</li><li>• Consultant + Entitlement Tranche</li><li>• Predevelopment Equity Tranche</li><li>• Construction Capital Stack</li></ul></div></section>
    <section className="rounded-xl border p-4"><h3 className="font-bold">Budget Burn vs Milestone Confidence</h3><ul className="mt-2 grid gap-1 text-sm md:grid-cols-2"><li>• Studies: Low Burn / High Learning Value</li><li>• Entitlement: Moderate Burn / Path-Defining</li><li>• DD + Permit: Higher Burn / Greater Execution Confidence</li><li>• Vertical Construction: Highest Burn / Full Delivery Phase</li></ul></section>
    <section className="rounded-xl bg-[#0d1b2a] p-5 text-white"><h3 className="text-xl font-bold">Construction Delivery Process</h3><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{['Preconstruction controls','Excavation + foundations','Shell','MEP','Interiors','Site finishes','CO + turnover'].map((s, i) => <div key={s} className="rounded-lg border border-[#d4af37]/50 p-2 text-sm">{i + 1}. {s}</div>)}</div></section>
    <section className="rounded-xl border border-[#d4af37]/60 bg-white p-6"><h3 className="text-2xl font-bold">Protected Downside, Preserved Upside</h3><p className="mt-2 text-sm">Execute the by-right path now while preserving disciplined entitlement optionality for future height expansion and capital upside.</p><div className="mt-4 grid gap-2 sm:grid-cols-3"><Link href="/project" className="rounded-lg bg-[#0d1b2a] px-3 py-2 text-center text-sm font-semibold text-white">Return to Project Overview</Link><a href="#scenario" className="rounded-lg border px-3 py-2 text-center text-sm font-semibold">Review Height Options</a><Link href="/contact" className="rounded-lg border px-3 py-2 text-center text-sm font-semibold">Schedule City Strategy Session</Link></div><p className="mt-4 rounded-lg bg-[#0d1b2a] p-3 text-sm font-medium text-[#f8fafc]"><span className="text-[#d4af37]">Fastest executable path:</span> Current zoning already supports a conservative 3-story execution path, allowing immediate progress while preserving future height optionality.</p></section>
  </div>
}
