'use client'
import Link from 'next/link'
import { useMemo, useState } from 'react'

// data omitted comments not used
const scenarios = [
  { id: '3', label: '3 Story', recommended: '3-Story By-Right + Preserve 6-Story Optionality', summary: ['By-right control case', 'Fastest executable path', 'Lowest entitlement complexity', 'Lowest capital intensity', 'Shortest construction duration'], value: 'Value creation at this stage increases PE underwriting confidence.', impacts: [{ label: 'Entitlement Intensity', value: 'Low' }, { label: 'Capital Coordination', value: 'Moderate' }, { label: 'Construction Duration', value: '14–18 months' }, { label: 'Delivery Complexity', value: 'Controlled' }] },
  { id: '6', label: '6 Story', recommended: '6-Story Rezoning Case with Structured Outreach', summary: ['Realistic rezoning path', 'Stronger unit count', 'Balanced timeline', 'Moderate entitlement lift'], value: 'Balanced upside supports stronger valuation while preserving execution discipline.', impacts: [{ label: 'Entitlement Intensity', value: 'Moderate' }, { label: 'Capital Coordination', value: 'Moderate/High' }, { label: 'Construction Duration', value: '18–22 months' }, { label: 'Delivery Complexity', value: 'Moderate' }] },
  { id: '8', label: '8 Story', recommended: '8-Story Optimized Yield with Early City Positioning', summary: ['Stronger condo stack', 'Improved IRR', 'Moderate/high entitlement complexity', 'Requires disciplined stakeholder coordination'], value: 'Higher yield potential requires stronger sequencing and entitlement control.', impacts: [{ label: 'Entitlement Intensity', value: 'Moderate/High' }, { label: 'Capital Coordination', value: 'High' }, { label: 'Construction Duration', value: '20–24 months' }, { label: 'Delivery Complexity', value: 'High' }] },
  { id: '10', label: '10 Story', recommended: '10-Story Maximum Upside Reserve Path', summary: ['Highest density', 'PE preferred upside case', 'Longest city path', 'Highest process complexity'], value: 'Maximum density can deliver strong upside, but requires prolonged city and capital coordination.', impacts: [{ label: 'Entitlement Intensity', value: 'High' }, { label: 'Capital Coordination', value: 'Very High' }, { label: 'Construction Duration', value: '22–28 months' }, { label: 'Delivery Complexity', value: 'Very High' }] }
]
const matrix = [
  ['3 Stories — By Right', ['Fastest path', 'Lowest entitlement risk', 'Supported by current zoning assumptions', 'Expected construction window: 14–18 months']],
  ['6 Stories — Moderate Lift', ['Realistic rezoning path', 'Stronger unit count', 'Balanced timeline', 'Expected construction window: 18–22 months']],
  ['8 Stories — Optimized Yield', ['Stronger condo stack', 'Improved IRR', 'Moderate/high entitlement complexity', 'Expected construction window: 20–24 months']],
  ['10 Stories — Maximum Upside', ['Highest density', 'PE preferred upside case', 'Longest city path', 'Expected construction window: 22–28 months']]
] as const
const phases = Array.from({ length: 13 }, (_, i) => ({ n: i + 1, t: ['Project Alignment','Site Studies + Due Diligence','Survey + ALTA / Title','Market + Product Validation','Capital Formation','Rezoning + City Strategy','Design Team Assembly','Concept Design + Massing','DD + Engineering','Permit + Financing','Preconstruction + Mobilization','Vertical Construction','Closeout + Exit'][i], s: i < 1 ? 'Complete' : i < 5 ? 'In Progress' : 'Queued', p: i < 1 ? 100 : i < 5 ? 35 + i * 7 : i === 5 ? 20 : 0 }))
const statusClass: Record<string, string> = { Complete: 'bg-emerald-100 text-emerald-800', 'In Progress': 'bg-amber-100 text-amber-800', Queued: 'bg-slate-200 text-slate-700' }

export default function RoadmapDashboard() {
  const [activeScenario, setActiveScenario] = useState('3')
  const active = useMemo(() => scenarios.find((s) => s.id === activeScenario) ?? scenarios[0], [activeScenario])

  return <div className="space-y-10 pb-14">
    <section className="rounded-2xl border border-[#d4af37]/50 bg-[#0d1b2a] p-6 text-[#f8fafc] md:p-8">
      <h1 className="text-3xl font-bold md:text-4xl">5501 E. 33rd Development Execution Roadmap</h1>
      <p className="mt-3 max-w-4xl text-sm text-slate-200 md:text-base">A disciplined project index for site diligence, entitlement strategy, capital sequencing, consultant coordination, and construction readiness.</p>
      <div className="mt-5 flex flex-wrap gap-2 text-xs font-semibold"><span className="rounded-full border border-[#d4af37]/60 px-3 py-1">Geotech reviewed</span><span className="rounded-full border border-[#d4af37]/60 px-3 py-1">ESA active</span><span className="rounded-full border border-[#d4af37]/60 px-3 py-1">Survey / title pending</span><span className="rounded-full border border-[#d4af37]/60 px-3 py-1">Height path under evaluation</span><span className="rounded-full border border-[#d4af37]/60 px-3 py-1">Capital narrative forming</span></div>
      <div className="mt-6 grid gap-3 sm:grid-cols-3"><Link href="/project" className="rounded-lg bg-white px-4 py-2 text-center text-sm font-semibold text-[#0d1b2a]">Return to Project Overview</Link><a href="#scenario" className="rounded-lg border border-[#d4af37] px-4 py-2 text-center text-sm font-semibold">Review Height Path Options</a><a href="#timeline" className="rounded-lg border border-[#d4af37] px-4 py-2 text-center text-sm font-semibold">Review Live Milestones</a></div>
    </section>
    <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-bold">Owner Action Dashboard</h2><ul className="mt-3 grid gap-2 text-sm md:grid-cols-2">{['Confirm preferred height path for early city discussions','Approve survey / title notice to proceed','Align community outreach language','Sequence architect and consultant input','Advance investor introductions and PE follow-up calls','Define next predevelopment budget tranche'].map((a) => <li key={a} className="rounded-lg bg-[#f8fafc] p-3">{a}</li>)}</ul></section>
    <section className="grid gap-3 md:grid-cols-3">{['Current Stage: Due Diligence + Market Validation','Site Studies: Geotech Reviewed / ESA Active','Entitlement: Pre-Rezoning Strategy','Capital: PE Outreach + Comp Validation','Design Readiness: Architect / GC Advisory Group Assembled','Construction Readiness: 3-Story By-Right Feasible'].map((c) => <div key={c} className="rounded-lg border border-[#d4af37]/60 bg-white p-4 text-sm font-medium">{c}</div>)}</section>
    <section id="scenario" className="space-y-4"><h2 className="text-2xl font-bold">Height Scenario Matrix</h2><div className="grid gap-4 md:grid-cols-2">{matrix.map(([title, bullets]) => <div key={title} className="rounded-xl border border-slate-200 bg-white p-4"><h3 className="font-semibold">{title}</h3><ul className="mt-2 space-y-1 text-sm text-slate-700">{bullets.map((b) => <li key={b}>• {b}</li>)}</ul></div>)}</div><div className="rounded-xl bg-[#0d1b2a] p-5 text-white"><div className="flex flex-wrap gap-2">{scenarios.map((s) => <button key={s.id} onClick={() => setActiveScenario(s.id)} className={`rounded-full px-3 py-1 text-sm ${activeScenario === s.id ? 'bg-[#d4af37] text-[#0d1b2a] font-semibold' : 'border border-slate-400'}`}>{s.label}</button>)}</div><p className="mt-4 text-sm font-semibold text-[#d4af37]">Recommended Today: {active.recommended}</p><ul className="mt-2 text-sm">{active.summary.map((s) => <li key={s}>• {s}</li>)}</ul><p className="mt-3 text-sm">{active.value}</p><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{active.impacts.map((i) => <div key={i.label} className="rounded-lg border border-[#d4af37]/40 p-2 text-xs"><p className="text-slate-300">{i.label}</p><p className="font-semibold">{i.value}</p></div>)}</div></div></section>
    <section className="rounded-xl bg-[#0d1b2a] p-4 text-white"><p className="text-center text-lg font-semibold">Cost certainty improves as unknowns are converted into decisions.</p></section>
    <section id="timeline" className="grid gap-4 lg:grid-cols-[220px_1fr]"><aside className="lg:sticky lg:top-20 lg:h-fit"><div className="flex gap-2 overflow-x-auto lg:block">{phases.map((p) => <a key={p.n} href={`#phase-${p.n}`} className="mb-2 block whitespace-nowrap rounded-full border border-slate-300 bg-white px-3 py-1 text-xs">Phase {p.n}</a>)}</div></aside><div className="space-y-3">{phases.map((p) => <article id={`phase-${p.n}`} key={p.n} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-bold">Phase {p.n}: {p.t}</h3><span className={`rounded-full px-2 py-1 text-xs font-semibold ${statusClass[p.s]}`}>{p.s}</span></div><div className="mt-2 h-2 rounded-full bg-slate-200"><div className="h-2 rounded-full bg-[#d4af37]" style={{ width: `${p.p}%` }} /></div><div className="mt-3 grid gap-2 text-sm md:grid-cols-2">{['Objective','Scope','Expected Working Window','Risk Watch','Decision Gate','Next Actions','Why This Phase Matters','Deliverables','Current Status','Capital Release Trigger','Documents','Updated Date'].map((k) => <p key={k}><span className="font-semibold">{k}:</span> {k === 'Updated Date' ? 'May 2026' : k === 'Expected Working Window' ? 'Path dependent by scenario and approvals.' : `${p.t} coordination detail.`}</p>)}</div></article>)}</div></section>
    <section className="grid gap-4 md:grid-cols-2"><div className="rounded-xl border p-4"><h3 className="font-bold">From Existing Zoning to Height Upside</h3><ol className="mt-2 grid gap-1 text-sm">{['Complete site studies','Complete survey + legal base','Confirm 3 / 6 / 8 / 10 massing paths','District outreach','Neighborhood positioning','Select preferred height path','Rezoning submission','City comments','Revisions','Approval path','Permit conversion'].map((s, i) => <li key={s}>{i + 1}. {s}</li>)}</ol></div><div className="rounded-xl border p-4"><h3 className="font-bold">City Review and Influence Path</h3><p className="mt-2 text-sm">District Office → Planning Staff → Neighborhood Positioning → Rezoning Review → Public Process → Council / Approval Path → Permit Conversion</p></div></section>
    <section className="rounded-xl bg-[#0d1b2a] p-5 text-white"><h3 className="text-xl font-bold">Live Market Intelligence</h3><div className="mt-3 grid gap-3 md:grid-cols-4">{['Condo Sales Validation','Workforce Rental Logic','Retail Frontage Assumptions','Exit Path Options'].map((x) => <div key={x} className="rounded-lg border border-[#d4af37]/40 p-3 text-sm">{x}</div>)}</div></section>
    <section className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{['Environmental legacy review','Tank closure verification','Entitlement risk','Parking / massing tradeoffs','Construction cost escalation','Appraisal gap','Capital close timing','Interest rate sensitivity'].map((r) => <div key={r} className="rounded-lg border bg-white p-3 text-sm">{r}</div>)}</div><div className="rounded-xl bg-[#0d1b2a] p-4 text-white"><p className="font-semibold">Parallel Workstreams</p><div className="mt-2 flex flex-wrap gap-2">{['PE outreach','City meetings','Architect interviews','GC benchmarking','ESA verification','Survey + title','Comp refresh','Neighborhood narrative','Lender conversations'].map((t) => <span key={t} className="rounded-full border border-[#d4af37]/50 px-3 py-1 text-xs">{t}</span>)}</div></div></section>
    <section className="grid gap-4 md:grid-cols-2"><div className="rounded-xl border p-4"><h3 className="font-bold">Owner Capital Exposure by Milestone</h3><ul className="mt-2 text-sm"><li>• Studies</li><li>• Design</li><li>• City / Entitlement</li><li>• Preconstruction</li></ul></div><div className="rounded-xl border p-4"><h3 className="font-bold">Capital Sequencing by Tranche</h3><ul className="mt-2 text-sm"><li>• Early Owner Soft Cost Tranche</li><li>• Consultant + Entitlement Tranche</li><li>• Predevelopment Equity Tranche</li><li>• Construction Capital Stack</li></ul></div></section>
    <section className="rounded-xl border p-4"><h3 className="font-bold">Budget Burn vs Milestone Confidence</h3><ul className="mt-2 grid gap-1 text-sm md:grid-cols-2"><li>• Studies: Low Burn / High Learning Value</li><li>• Entitlement: Moderate Burn / Path-Defining</li><li>• DD + Permit: Higher Burn / Greater Execution Confidence</li><li>• Vertical Construction: Highest Burn / Full Delivery Phase</li></ul></section>
    <section className="rounded-xl bg-[#0d1b2a] p-5 text-white"><h3 className="text-xl font-bold">Construction Delivery Process</h3><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{['Preconstruction controls','Excavation + foundations','Shell','MEP','Interiors','Site finishes','CO + turnover'].map((s, i) => <div key={s} className="rounded-lg border border-[#d4af37]/50 p-2 text-sm">{i + 1}. {s}</div>)}</div></section>
    <section className="rounded-xl border border-[#d4af37]/60 bg-white p-6"><h3 className="text-2xl font-bold">Protected Downside, Preserved Upside</h3><p className="mt-2 text-sm">Execute the by-right path now while preserving disciplined entitlement optionality for future height expansion and capital upside.</p><div className="mt-4 grid gap-2 sm:grid-cols-3"><Link href="/project" className="rounded-lg bg-[#0d1b2a] px-3 py-2 text-center text-sm font-semibold text-white">Return to Project Overview</Link><a href="#scenario" className="rounded-lg border px-3 py-2 text-center text-sm font-semibold">Review Height Options</a><Link href="/contact" className="rounded-lg border px-3 py-2 text-center text-sm font-semibold">Schedule City Strategy Session</Link></div><p className="mt-4 rounded-lg bg-[#0d1b2a] p-3 text-sm font-medium text-[#f8fafc]"><span className="text-[#d4af37]">Fastest executable path:</span> Current zoning already supports a conservative 3-story execution path, allowing immediate progress while preserving future height optionality.</p></section>
  </div>
}
